server:
  port: 9020
  jetty:
    accessors:
      append: true

spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 1024MB
  profiles:
    active: ${PROFILE:dev}
  application:
    name: course-admin-server
  jackson:
    default-property-inclusion:
      date-format: "yyyy-MM-dd HH:mm:ss"
      time-zone: "GMT+8"
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://ec2-52-221-223-231.ap-southeast-1.compute.amazonaws.com:3306/course?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    redis:
      database: 0
      host: ec2-52-221-223-231.ap-southeast-1.compute.amazonaws.com
      port: 6379
      password: 123456
      jedis:
        pool:
          #最大连接数
          max-active: 8
          #最大阻塞等待时间(负数表示没限制)
          max-wait: -1
          #最大空闲
          max-idle: 8
          #最小空闲
          min-idle: 0
          #连接超时时间
      timeout: 10000
  flyway:
    table: migrations
    enabled: false
    baseline-on-migrate: true
    clean-disabled: true
    sql-migration-prefix: v
    baseline-version: 1.0.0
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}
mybatis-plus:
  mapper-locations: classpath*:com/ltg/base/**/mapper/xml/**.xml

knife4j:
  enable: true
  setting:
    language: zh-CN
    swagger-model-name: 实体类列表
app:
  login:
    filter-excludeUrl:
      - /
      - /api/v1/account/**
      - /api/v1/file/**
      - /logo.png
    filter-includeUrl:
      - /api/v1/**
  storage:
    # 配置本地文件储存库位置
    local-prefix: E:\company\code\files
    domain: http://127.0.0.1:9999