version: "3.6"
services:
  consumer-course-server:
    image: IMAGE_NAME
    container_name: consumer-course-server
    hostname: consumer-course-server
    network_mode: host
    volumes:
      - /home/course/data:/volume:rw
    environment:
      PROFILE: prod
    restart: always