version: "3.6"
services:
  course-login-server:
    image: course-login-server:latest
    container_name: course-login-server
    hostname: course-login-server
    network_mode: host
    volumes:
      - /home/course/data:/volume:rw
    environment:
      PROFILE: prod
    restart: always